---
blank_issues_enabled: false
contact_links:
  - name: DAOhaus Homepage
    url: https://daohaus.club/
    about: Learn more about DAOhaus
  - name: DAOhaus Discord
    url: https://discord.gg/kJaVkXtsXA
    about: 'Join our discord and report issues in #support'
  - name: DAOhaus Developer Docs and Contribution Guidelines
    url: https://docs.daohaus.club/
    about: 'Learn about developing for DAOhaus'
